# 詳細については、Dockerfile.debianのコメントを参照。
FROM --platform=$BUILDPLATFORM node:18-alpine AS client-builder
COPY client/package*.json /app/client/
WORKDIR /app/client
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm install --no-save --loglevel=info
COPY . /app/
RUN npm run build --loglevel=info

FROM node:18-alpine3.19 AS server-builder
RUN apk add --no-cache g++ make pkgconf python3 py3-pip
# node-sqlite3 が依存する node-gyp が が依存する python3 の distutils 廃止に対応
# node-sqlite3 が依存する node-gyp が v10 以上になれば不要になる
RUN pip install --break-system-pack setuptools
WORKDIR /app
COPY package*.json /app/
ENV DOCKER="YES"
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm install --no-save --loglevel=info
COPY . .
RUN rm -rf client
RUN npm run build-server --loglevel=info
# devDependencies を除去し、実行時に必要な dependencies のみ残す
RUN npm prune --omit=dev

FROM node:18-alpine
LABEL maintainer="l3tnun"
WORKDIR /app

# webpack バンドル
COPY --from=server-builder /app/dist /app/dist/

# 実行時に必要なファイル
COPY --from=server-builder /app/api.yml /app/api.yml
COPY --from=server-builder /app/package.json /app/package.json
COPY --from=server-builder /app/config /app/config/
COPY --from=server-builder /app/img /app/img/

# dependencies のみの node_modules をコピー
COPY --from=server-builder /app/node_modules /app/node_modules/

# client
COPY --from=client-builder /app/client /app/client/

EXPOSE 8888
ENTRYPOINT ["npm"]
CMD ["start"]
